### ISSUE TITLE
Table declaration should verify that class name is valid

### ISSUE THREAD

**Issue by stpierrelab** [datajoint/datajoint-matlab#115]
Hi, 
I'm setting up DataJoint on MATLAB r2017b with HeidiSQL 9.5. When I create a schema on local machine, following the tutorial, I get the following error "The specified key is not present in this container.", while the table is successfully created on the server. 
Thanks in advance for resolving the issue. 

```
>> dj.createSchema
Enter database name >> test
database created
Please select a package folder. Opening UI...
>> test.fov()

ans = 


Object test.fov


<SQL>
CREATE TABLE `test`.`fov` (
`id` int                   NOT NULL COMMENT "unique mouse id",
`dob` date                       NOT NULL COMMENT "mouse date of birth",
`sex` enum('M', 'F', 'U') NOT NULL COMMENT "sex of mouse - Male, Female, or Unknown/Unclassified",
PRIMARY KEY (`id`)
) ENGINE = InnoDB, COMMENT "fov"
</SQL>

Error using containers.Map/subsref
The specified key is not present in this container.

Error in dj.internal.Table/get.plainTableName (line 115)
                self.plainTableName = self.schema.tableNames(self.className);

Error in dj.internal.Table/get.tableHeader (line 81)
                self.tableHeader = self.schema.headers(self.plainTableName);

Error in dj.internal.GeneralRelvar/compile (line 659)
                    header = derive(tab.tableHeader);

Error in dj.internal.GeneralRelvar/get.header (line 43)
            header = self.compile;

Error in dj.internal.GeneralRelvar/disp (line 73)
            hdr = self.header;
```

In the fov.m
```
%{
# fov
id: int                  # unique mouse id
---
dob: date                      # mouse date of birth
sex: enum('M', 'F', 'U')       # sex of mouse - Male, Female, or Unknown/Unclassified
%}

classdef fov < dj.Manual    
end
```

**Comment by dimitri-yatsenko** [comment]
Class names must be capitalized.   Yes, the error message should be more informative.

**Comment by eywalker** [comment]
Hi @stpierrelab thanks for reporting this. This is caused by the fact your class name `fov` is considered to be an invalid class name under DataJoint. DataJoint expects the class name to start with a capital letter. To fix your issue quickly, rename the class file and the name of the class (in the line `classdef ...`) to `Fov` and you should be able to work with that table you created. 

I'll double check all the tutorials to make sure that we follow the correct conventions for the class name, and we'll improve the  check and error message during the table creation.

**Comment by stpierrelab** [comment]
@dimitri-yatsenko @eywalker Thanks for the quick reply. Your quick fix works!
