### ISSUE TITLE
Computed (but not stored) fields

### ISSUE THREAD

**Issue by wrongu** [datajoint/datajoint-matlab#71]
Apologies if this feature, or a reason for its absence, is documented somewhere - I couldn't find it.

For some large fields, you might consider a trade-off between storage space and time to regenerate it on demand. For example, with large images generated from a random seed, you might only store the seed in the DB and reconstruct the image each time it is needed during analysis. Of course, with DJ you can still do this by keeping reconstruction code separate and storing only the seed, but it would be semantically "nice" to be able to `fetch()` a field from a table that is recomputed each time.

**Comment by dimitri-yatsenko** [comment]
Yes, many things can and should be computed on the fly rather than being stored.  Currently this can be done in a number of ways and I am not sure if binding this into `fetch` would be the cleanest option.  For example, how would users know that this extra field is available? Would it be included in the table declaration?  Would you like to flesh this out a bit?

**Comment by wrongu** [comment]
I mentioned `fetch` because it was the first thing that comes to mind. I liked the idea of updating the table declaration (e.g. annotated with a new `'volatile'` data type) so that in a given table/class, all fields and their descriptions appear in the same place. To compute these fields would require some extra callbacks and indirection, so you're right that it's probably not the cleanest option.

A cleaner option, perhaps, would be to simply describe extra fields as comments in the declaration, then make my own `get_xyz(self, key)` function for each field `xyz`.

**Comment by dimitri-yatsenko** [comment]
The `self.get_xyz(key)` solution is what people do now.  You must be careful though since sequential `fetch` calls are not guaranteed to return the same things in the same order.  So if you need other attributes from the same table along with `xyz`, you better get them in one fetch and then compute `xyz` for each item in the sequence.

**Comment by wrongu** [comment]
Thanks!
